//export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const LOAD_TASKS_SUCCESS = 'LOAD_TASK_SUCCESS';

export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const LOAD_RECIPES_SUCCESS = 'LOAD_RECIPE_SUCCESS';

export const CREATE_GROCERY_SUCCESS = 'CREATE_GROCERY_SUCCESS';
export const LOAD_GROCERIES_SUCCESS = 'LOAD_GROCERY_SUCCESS';
